#############################################################################
# Makefile for building: trendigital
# Generated by qmake (2.01a) (Qt 4.6.3) on: dt. oct. 4 11:16:06 2011
# Project:  trendigital.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile trendigital.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtSql -I/usr/include/qt4/Qt3Support -I/usr/include/qt4 -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQt3Support -lQtSql -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/document.cpp \
		src/dialogs/editlokos.cpp \
		src/dialogs/lokotabbar.cpp \
		src/dialogs/lokodock.cpp \
		src/loko.cpp \
		src/database.cpp \
		src/dialogs/iconview.cpp \
		src/cell.cpp \
		src/element.cpp \
		src/program.cpp \
		src/route.cpp \
		src/lokocommands.cpp \
		src/conditions.cpp \
		src/view.cpp \
		src/plugindialog.cpp \
		src/traininterface.cpp \
		src/debug.cpp moc_mainwindow.cpp \
		moc_editlokos.cpp \
		moc_lokotabbar.cpp \
		moc_lokodock.cpp \
		moc_database.cpp \
		moc_iconview.cpp \
		moc_view.cpp \
		moc_plugindialog.cpp \
		qrc_icons.cpp \
		qrc_bitmaps.cpp
OBJECTS       = main.o \
		mainwindow.o \
		document.o \
		editlokos.o \
		lokotabbar.o \
		lokodock.o \
		loko.o \
		database.o \
		iconview.o \
		cell.o \
		element.o \
		program.o \
		route.o \
		lokocommands.o \
		conditions.o \
		view.o \
		plugindialog.o \
		traininterface.o \
		debug.o \
		moc_mainwindow.o \
		moc_editlokos.o \
		moc_lokotabbar.o \
		moc_lokodock.o \
		moc_database.o \
		moc_iconview.o \
		moc_view.o \
		moc_plugindialog.o \
		qrc_icons.o \
		qrc_bitmaps.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		trendigital.pro
QMAKE_TARGET  = trendigital
DESTDIR       = 
TARGET        = trendigital

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_editlokos.h ui_lokotabbar.h ui_lokodock.h ui_iconview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: trendigital.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQt3Support.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile trendigital.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQt3Support.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile trendigital.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/trendigital1.0.0 || $(MKDIR) .tmp/trendigital1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/trendigital1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/document.h src/dialogs/editlokos.h src/general.h src/dialogs/lokotabbar.h src/dialogs/lokodock.h src/loko.h src/database.h src/dialogs/iconview.h src/cell.h src/element.h src/program.h src/route.h src/lokocommands.h src/conditions.h src/view.h src/plugindialog.h src/traininterface.h src/debug.h .tmp/trendigital1.0.0/ && $(COPY_FILE) --parents icons.qrc bitmaps.qrc .tmp/trendigital1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/document.cpp src/dialogs/editlokos.cpp src/dialogs/lokotabbar.cpp src/dialogs/lokodock.cpp src/loko.cpp src/database.cpp src/dialogs/iconview.cpp src/cell.cpp src/element.cpp src/program.cpp src/route.cpp src/lokocommands.cpp src/conditions.cpp src/view.cpp src/plugindialog.cpp src/traininterface.cpp src/debug.cpp .tmp/trendigital1.0.0/ && $(COPY_FILE) --parents src/mainwindow.ui src/dialogs/editlokos.ui src/dialogs/lokotabbar.ui src/dialogs/lokodock.ui src/dialogs/iconview.ui .tmp/trendigital1.0.0/ && (cd `dirname .tmp/trendigital1.0.0` && $(TAR) trendigital1.0.0.tar trendigital1.0.0 && $(COMPRESS) trendigital1.0.0.tar) && $(MOVE) `dirname .tmp/trendigital1.0.0`/trendigital1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/trendigital1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_editlokos.cpp moc_lokotabbar.cpp moc_lokodock.cpp moc_database.cpp moc_iconview.cpp moc_view.cpp moc_plugindialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_editlokos.cpp moc_lokotabbar.cpp moc_lokodock.cpp moc_database.cpp moc_iconview.cpp moc_view.cpp moc_plugindialog.cpp
moc_mainwindow.cpp: src/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/mainwindow.h -o moc_mainwindow.cpp

moc_editlokos.cpp: src/dialogs/editlokos.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/editlokos.h -o moc_editlokos.cpp

moc_lokotabbar.cpp: src/dialogs/lokotabbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/lokotabbar.h -o moc_lokotabbar.cpp

moc_lokodock.cpp: src/dialogs/lokodock.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/lokodock.h -o moc_lokodock.cpp

moc_database.cpp: src/database.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/database.h -o moc_database.cpp

moc_iconview.cpp: src/dialogs/iconview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/dialogs/iconview.h -o moc_iconview.cpp

moc_view.cpp: src/view.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/view.h -o moc_view.cpp

moc_plugindialog.cpp: src/plugindialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/plugindialog.h -o moc_plugindialog.cpp

compiler_rcc_make_all: qrc_icons.cpp qrc_bitmaps.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_bitmaps.cpp
qrc_icons.cpp: icons.qrc \
		images/icons/media-playback-pause.png \
		images/icons/go-down.png \
		images/icons/media-skip-backward.png \
		images/icons/dialog-warning.png \
		images/icons/preview-file.png \
		images/icons/go-up.png \
		images/icons/process-stop.png \
		images/icons/system-run.png \
		images/icons/applications-development.png \
		images/icons/stock_keyring.png \
		images/icons/sleep.png \
		images/icons/help-contents.png \
		images/icons/logviewer.png \
		images/icons/address-book-new.png \
		images/icons/go-next.png \
		images/icons/go-top.png \
		images/icons/gtk-edit.png \
		images/icons/document-save.png \
		images/icons/appointment-new.png \
		images/icons/go-bottom.png \
		images/icons/document-save-as.png \
		images/icons/gtk-info.png \
		images/icons/media-skip-forward.png \
		images/icons/list-add.png \
		images/icons/go-last.png \
		images/icons/document-page-setup.png \
		images/icons/media-seek-backward.png \
		images/icons/go-first.png \
		images/icons/help-about.png \
		images/icons/media-playback-start.png \
		images/icons/window-close.png \
		images/icons/edit-clear.png \
		images/icons/clock.png \
		images/icons/system-shutdown.png \
		images/icons/document-print.png \
		images/icons/tren-digital.png \
		images/icons/go-previous.png \
		images/icons/media-seek-forward.png \
		images/icons/edit-find-replace.png \
		images/icons/document-new.png \
		images/icons/notification-audio-stop.png \
		images/icons/document-open.png \
		images/icons/document-properties.png \
		images/icons/view-refresh.png \
		images/icons/edit-find.png
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

qrc_bitmaps.cpp: bitmaps.qrc \
		images/bitmaps/plataforma_39010_11.png \
		images/bitmaps/Signal_34004_1.png \
		images/bitmaps/Common_33013_0.png \
		images/bitmaps/SimpleSlip_36306_0.png \
		images/bitmaps/EndTrack_37002_0.png \
		images/bitmaps/SimpleSlip_36400_3.png \
		images/bitmaps/plataforma_39010_20.png \
		images/bitmaps/TripleSwitch_36020_1.png \
		images/bitmaps/TripleSwitch_36022_2.png \
		images/bitmaps/Signal_35011_0.png \
		images/bitmaps/plataforma_39010_1.png \
		images/bitmaps/Detour_36001_0.png \
		images/bitmaps/DoubleSlip_36202_2.png \
		images/bitmaps/SimpleSlip_36402_1.png \
		images/bitmaps/SimpleSlip_36405_0.png \
		images/bitmaps/Signal_35004_0.png \
		images/bitmaps/Detour_36012_0.png \
		images/bitmaps/Common_33025_0.png \
		images/bitmaps/Detour_36004_1.png \
		images/bitmaps/Signal_34003_1.png \
		images/bitmaps/TripleSwitch_36018_0.png \
		images/bitmaps/SimpleSlip_36302_1.png \
		images/bitmaps/Common_33016_0.png \
		images/bitmaps/SimpleSlip_36305_0.png \
		images/bitmaps/EndTrack_37001_0.png \
		images/bitmaps/Signal_34014_0.png \
		images/bitmaps/Common_33003_0.png \
		images/bitmaps/DoubleSlip_36103_1.png \
		images/bitmaps/Signal_34010_0.png \
		images/bitmaps/DoubleSlip_36201_2.png \
		images/bitmaps/DoubleSlip_36203_1.png \
		images/bitmaps/SimpleSlip_36404_0.png \
		images/bitmaps/Signal_35003_0.png \
		images/bitmaps/Signal_35000_1.png \
		images/bitmaps/Detour_36011_0.png \
		images/bitmaps/Detour_36008_0.png \
		images/bitmaps/plataforma_39001_0.png \
		images/bitmaps/Detour_36003_1.png \
		images/bitmaps/Signal_34006_1.png \
		images/bitmaps/plataforma_39004_2.png \
		images/bitmaps/Common_33015_0.png \
		images/bitmaps/SimpleSlip_36304_0.png \
		images/bitmaps/EndTrack_37000_0.png \
		images/bitmaps/Detour_36014_1.png \
		images/bitmaps/plataforma_39010_23.png \
		images/bitmaps/Signal_34013_0.png \
		images/bitmaps/DoubleSlip_36102_1.png \
		images/bitmaps/TripleSwitch_36022_1.png \
		images/bitmaps/Speaker.png \
		images/bitmaps/DoubleSlip_36200_2.png \
		images/bitmaps/DoubleSlip_36202_1.png \
		images/bitmaps/Signal_34002_0.png \
		images/bitmaps/SimpleSlip_36403_0.png \
		images/bitmaps/Signal_35006_0.png \
		images/bitmaps/Detour_36006_1.png \
		images/bitmaps/Signal_34005_1.png \
		images/bitmaps/Common_33020_0.png \
		images/bitmaps/SimpleSlip_36303_0.png \
		images/bitmaps/plataforma_39010_15.png \
		images/bitmaps/Cross_37009_0.png \
		images/bitmaps/Detour_36013_1.png \
		images/bitmaps/Signal_34014_3.png \
		images/bitmaps/DoubleSlip_36101_1.png \
		images/bitmaps/Signal_34008_2.png \
		images/bitmaps/TripleSwitch_36021_2.png \
		images/bitmaps/SimpleSlip_36401_2.png \
		images/bitmaps/Signal_34010_3.png \
		images/bitmaps/plataforma_39010_5.png \
		images/bitmaps/DoubleSlip_36201_1.png \
		images/bitmaps/Signal_34001_0.png \
		images/bitmaps/Signal_35005_0.png \
		images/bitmaps/Cross_37013_0.png \
		images/bitmaps/plataforma_39001_3.png \
		images/bitmaps/Detour_36005_1.png \
		images/bitmaps/Connector.png \
		images/bitmaps/Signal_34015_0.png \
		images/bitmaps/Signal_34013_3.png \
		images/bitmaps/DoubleSlip_36100_1.png \
		images/bitmaps/Signal_34007_2.png \
		images/bitmaps/SimpleSlip_36400_2.png \
		images/bitmaps/SimpleSlip_36401_1.png \
		images/bitmaps/DoubleSlip_36200_1.png \
		images/bitmaps/Cross_37010_0.png \
		images/bitmaps/SimpleSlip_36301_1.png \
		images/bitmaps/SimpleSlip_36402_0.png \
		images/bitmaps/Detour_36000_1.png \
		images/bitmaps/plataforma_39001_4.png \
		images/bitmaps/Signal_35014_1.png \
		images/bitmaps/Detour_36015_1.png \
		images/bitmaps/Signal_34000_1.png \
		images/bitmaps/SimpleSlip_36302_0.png \
		images/bitmaps/plataforma_39010_17.png \
		images/bitmaps/TripleSwitch_36021_1.png \
		images/bitmaps/Signal_35010_1.png \
		images/bitmaps/Common_33000_0.png \
		images/bitmaps/SimpleSlip_36400_1.png \
		images/bitmaps/SimpleSlip_36300_1.png \
		images/bitmaps/Signal_34012_2.png \
		images/bitmaps/Signal_35000_0.png \
		images/bitmaps/Common_39003_0.png \
		images/bitmaps/Signal_35013_1.png \
		images/bitmaps/Detour_36010_1.png \
		images/bitmaps/Signal_34015_3.png \
		images/bitmaps/Signal_34009_2.png \
		images/bitmaps/TripleSwitch_36018_2.png \
		images/bitmaps/plataforma_39010_18.png \
		images/bitmaps/Signal_35002_1.png \
		images/bitmaps/plataforma_39010_9.png \
		images/bitmaps/TripleSwitch_36017_0.png \
		images/bitmaps/Cross_37012_0.png \
		images/bitmaps/Detour_36002_1.png \
		images/bitmaps/Signal_34011_2.png \
		images/bitmaps/DoubleSlip_36203_3.png \
		images/bitmaps/plataforma_39010_12.png \
		images/bitmaps/Signal_34004_2.png \
		images/bitmaps/plataforma_39004_0.png \
		images/bitmaps/plataforma_39010_21.png \
		images/bitmaps/Signal_35001_1.png \
		images/bitmaps/Common_33022_0.png \
		images/bitmaps/plataforma_39010_2.png \
		images/bitmaps/Detour_36001_1.png \
		images/bitmaps/DoubleSlip_36202_3.png \
		images/bitmaps/Common_39005_0.png \
		images/bitmaps/Signal_35015_1.png \
		images/bitmaps/Detour_36012_1.png \
		images/bitmaps/Signal_34003_2.png \
		images/bitmaps/TripleSwitch_36018_1.png \
		images/bitmaps/Signal_34014_1.png \
		images/bitmaps/Signal_34008_0.png \
		images/bitmaps/SimpleSlip_36401_0.png \
		images/bitmaps/TripleSwitch_36019_0.png \
		images/bitmaps/Common_33021_0.png \
		images/bitmaps/Signal_34010_1.png \
		images/bitmaps/DoubleSlip_36201_3.png \
		images/bitmaps/Common_33012_0.png \
		images/bitmaps/SimpleSlip_36301_0.png \
		images/bitmaps/Detour_36011_1.png \
		images/bitmaps/SimpleSlip_36407_3.png \
		images/bitmaps/Detour_36008_1.png \
		images/bitmaps/plataforma_39001_1.png \
		images/bitmaps/Signal_34006_2.png \
		images/bitmaps/plataforma_39004_3.png \
		images/bitmaps/Signal_35014_0.png \
		images/bitmaps/Signal_34013_1.png \
		images/bitmaps/Signal_34007_0.png \
		images/bitmaps/Signal_35010_0.png \
		images/bitmaps/SimpleSlip_36400_0.png \
		images/bitmaps/TripleSwitch_36016_0.png \
		images/bitmaps/Cross_37011_0.png \
		images/bitmaps/DoubleSlip_36200_3.png \
		images/bitmaps/Signal_34002_1.png \
		images/bitmaps/Common_33011_0.png \
		images/bitmaps/SimpleSlip_36300_0.png \
		images/bitmaps/Detach_33004_0.png \
		images/bitmaps/SimpleSlip_36406_3.png \
		images/bitmaps/Common_39000_0.png \
		images/bitmaps/Common_33002_0.png \
		images/bitmaps/Signal_34005_2.png \
		images/bitmaps/Signal_35013_0.png \
		images/bitmaps/plataforma_39004_4.png \
		images/bitmaps/Detour_36007_0.png \
		images/bitmaps/Signal_34008_3.png \
		images/bitmaps/Signal_35002_0.png \
		images/bitmaps/plataforma_39010_6.png \
		images/bitmaps/Signal_34001_1.png \
		images/bitmaps/SimpleSlip_36405_3.png \
		images/bitmaps/Signal_34012_0.png \
		images/bitmaps/Common_33001_0.png \
		images/bitmaps/Signal_34015_1.png \
		images/bitmaps/Signal_34009_0.png \
		images/bitmaps/Signal_35001_0.png \
		images/bitmaps/TripleSwitch_36023_0.png \
		images/bitmaps/Detach_33006_0.png \
		images/bitmaps/SimpleSlip_36404_3.png \
		images/bitmaps/TripleSwitch_36017_2.png \
		images/bitmaps/Signal_34011_0.png \
		images/bitmaps/Signal_35015_0.png \
		images/bitmaps/Signal_34000_2.png \
		images/bitmaps/Signal_35008_1.png \
		images/bitmaps/Detour_36009_0.png \
		images/bitmaps/plataforma_39010_10.png \
		images/bitmaps/Signal_34004_0.png \
		images/bitmaps/TripleSwitch_36020_0.png \
		images/bitmaps/Detach_33005_0.png \
		images/bitmaps/SimpleSlip_36403_3.png \
		images/bitmaps/plataforma_39010_0.png \
		images/bitmaps/Signal_34012_3.png \
		images/bitmaps/SimpleSlip_36407_2.png \
		images/bitmaps/Signal_35007_1.png \
		images/bitmaps/Detour_36004_0.png \
		images/bitmaps/Signal_34003_0.png \
		images/bitmaps/Signal_34009_3.png \
		images/bitmaps/plataforma_39010_19.png \
		images/bitmaps/DoubleSlip_36103_0.png \
		images/bitmaps/TripleSwitch_36017_1.png \
		images/bitmaps/TripleSwitch_36019_2.png \
		images/bitmaps/Signal_34011_3.png \
		images/bitmaps/DoubleSlip_36203_0.png \
		images/bitmaps/SimpleSlip_36406_2.png \
		images/bitmaps/GO.png \
		images/bitmaps/SimpleSlip_36407_1.png \
		images/bitmaps/Detour_36003_0.png \
		images/bitmaps/plataforma_39010_13.png \
		images/bitmaps/Signal_34006_0.png \
		images/bitmaps/plataforma_39004_1.png \
		images/bitmaps/Detour_36014_0.png \
		images/bitmaps/Common_33027_0.png \
		images/bitmaps/SimpleSlip_36307_1.png \
		images/bitmaps/plataforma_39010_22.png \
		images/bitmaps/DoubleSlip_36102_0.png \
		images/bitmaps/Common_39002_0.png \
		images/bitmaps/TripleSwitch_36022_0.png \
		images/bitmaps/Common_33018_0.png \
		images/bitmaps/EndTrack_37007_0.png \
		images/bitmaps/Detach_33007_0.png \
		images/bitmaps/TripleSwitch_36016_2.png \
		images/bitmaps/Signal_35012_1.png \
		images/bitmaps/Luz.png \
		images/bitmaps/plataforma_39010_3.png \
		images/bitmaps/Cross_37008_0.png \
		images/bitmaps/DoubleSlip_36202_0.png \
		images/bitmaps/Stop.png \
		images/bitmaps/SimpleSlip_36402_3.png \
		images/bitmaps/SimpleSlip_36405_2.png \
		images/bitmaps/SimpleSlip_36406_1.png \
		images/bitmaps/Signal_35009_1.png \
		images/bitmaps/Detour_36006_0.png \
		images/bitmaps/Signal_34005_0.png \
		images/bitmaps/plataforma_39010_14.png \
		images/bitmaps/Detour_36013_0.png \
		images/bitmaps/SimpleSlip_36306_1.png \
		images/bitmaps/Signal_34014_2.png \
		images/bitmaps/DoubleSlip_36101_0.png \
		images/bitmaps/Signal_34008_1.png \
		images/bitmaps/Common_33017_0.png \
		images/bitmaps/EndTrack_37006_0.png \
		images/bitmaps/TripleSwitch_36019_1.png \
		images/bitmaps/Signal_35011_1.png \
		images/bitmaps/Signal_34010_2.png \
		images/bitmaps/Common_33008_0.png \
		images/bitmaps/plataforma_39010_4.png \
		images/bitmaps/DoubleSlip_36201_0.png \
		images/bitmaps/SimpleSlip_36404_2.png \
		images/bitmaps/SimpleSlip_36405_1.png \
		images/bitmaps/Signal_35004_1.png \
		images/bitmaps/plataforma_39001_2.png \
		images/bitmaps/Detour_36005_0.png \
		images/bitmaps/Signal_35008_0.png \
		images/bitmaps/SimpleSlip_36305_1.png \
		images/bitmaps/Signal_34013_2.png \
		images/bitmaps/DoubleSlip_36100_0.png \
		images/bitmaps/Signal_34007_1.png \
		images/bitmaps/EndTrack_37005_0.png \
		images/bitmaps/TripleSwitch_36016_1.png \
		images/bitmaps/DoubleSlip_36200_0.png \
		images/bitmaps/Signal_34002_2.png \
		images/bitmaps/SimpleSlip_36403_2.png \
		images/bitmaps/TripleSwitch_36023_2.png \
		images/bitmaps/SimpleSlip_36404_1.png \
		images/bitmaps/Signal_35003_1.png \
		images/bitmaps/Detour_36000_0.png \
		images/bitmaps/Signal_35007_0.png \
		images/bitmaps/Detour_36015_0.png \
		images/bitmaps/Common_33024_0.png \
		images/bitmaps/SimpleSlip_36304_1.png \
		images/bitmaps/Signal_34000_0.png \
		images/bitmaps/Detour_36007_1.png \
		images/bitmaps/plataforma_39010_16.png \
		images/bitmaps/TripleSwitch_36021_0.png \
		images/bitmaps/Common_33019_0.png \
		images/bitmaps/EndTrack_37004_0.png \
		images/bitmaps/plataforma_39010_7.png \
		images/bitmaps/Signal_34001_2.png \
		images/bitmaps/TripleSwitch_36020_2.png \
		images/bitmaps/SimpleSlip_36403_1.png \
		images/bitmaps/Signal_35006_1.png \
		images/bitmaps/Signal_34012_1.png \
		images/bitmaps/SimpleSlip_36407_0.png \
		images/bitmaps/Detour_36010_0.png \
		images/bitmaps/Common_33023_0.png \
		images/bitmaps/SimpleSlip_36303_1.png \
		images/bitmaps/Signal_34015_2.png \
		images/bitmaps/Signal_34009_1.png \
		images/bitmaps/Common_33014_0.png \
		images/bitmaps/SimpleSlip_36307_0.png \
		images/bitmaps/EndTrack_37003_0.png \
		images/bitmaps/SimpleSlip_36401_3.png \
		images/bitmaps/Common_33009_0.png \
		images/bitmaps/Common_33010_0.png \
		images/bitmaps/TripleSwitch_36023_1.png \
		images/bitmaps/Signal_35012_0.png \
		images/bitmaps/plataforma_39010_8.png \
		images/bitmaps/ArrowUp.png \
		images/bitmaps/Signal_35005_1.png \
		images/bitmaps/SimpleSlip_36402_2.png \
		images/bitmaps/Detour_36002_0.png \
		images/bitmaps/Signal_34011_1.png \
		images/bitmaps/DoubleSlip_36203_2.png \
		images/bitmaps/SimpleSlip_36406_0.png \
		images/bitmaps/ArrowDown.png \
		images/bitmaps/Signal_35009_0.png \
		images/bitmaps/Common_33026_0.png \
		images/bitmaps/Detour_36009_1.png
	/usr/bin/rcc -name bitmaps bitmaps.qrc -o qrc_bitmaps.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_editlokos.h ui_lokotabbar.h ui_lokodock.h ui_iconview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_editlokos.h ui_lokotabbar.h ui_lokodock.h ui_iconview.h
ui_mainwindow.h: src/mainwindow.ui \
		view.h \
		src/view.h
	/usr/bin/uic-qt4 src/mainwindow.ui -o ui_mainwindow.h

ui_editlokos.h: src/dialogs/editlokos.ui
	/usr/bin/uic-qt4 src/dialogs/editlokos.ui -o ui_editlokos.h

ui_lokotabbar.h: src/dialogs/lokotabbar.ui
	/usr/bin/uic-qt4 src/dialogs/lokotabbar.ui -o ui_lokotabbar.h

ui_lokodock.h: src/dialogs/lokodock.ui
	/usr/bin/uic-qt4 src/dialogs/lokodock.ui -o ui_lokodock.h

ui_iconview.h: src/dialogs/iconview.ui
	/usr/bin/uic-qt4 src/dialogs/iconview.ui -o ui_iconview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/general.h \
		src/lokocommands.h \
		src/conditions.h \
		src/route.h \
		src/program.h \
		src/loko.h \
		src/element.h \
		src/cell.h \
		src/document.h \
		src/traininterface.h \
		src/plugindialog.h \
		src/debug.h \
		src/mainwindow.h \
		ui_mainwindow.h \
		src/dialogs/lokotabbar.h \
		src/dialogs/lokodock.h \
		src/dialogs/editlokos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

document.o: src/document.cpp src/general.h \
		src/loko.h \
		src/element.h \
		src/cell.h \
		src/lokocommands.h \
		src/conditions.h \
		src/route.h \
		src/program.h \
		src/mainwindow.h \
		src/document.h \
		src/debug.h \
		src/traininterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o src/document.cpp

editlokos.o: src/dialogs/editlokos.cpp src/general.h \
		src/dialogs/editlokos.h \
		ui_editlokos.h \
		src/loko.h \
		src/dialogs/iconview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editlokos.o src/dialogs/editlokos.cpp

lokotabbar.o: src/dialogs/lokotabbar.cpp src/general.h \
		src/dialogs/lokodock.h \
		src/loko.h \
		src/element.h \
		src/cell.h \
		src/document.h \
		src/mainwindow.h \
		src/dialogs/lokotabbar.h \
		ui_lokotabbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lokotabbar.o src/dialogs/lokotabbar.cpp

lokodock.o: src/dialogs/lokodock.cpp src/dialogs/lokodock.h \
		ui_lokodock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lokodock.o src/dialogs/lokodock.cpp

loko.o: src/loko.cpp src/general.h \
		src/dialogs/lokodock.h \
		src/mainwindow.h \
		src/loko.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loko.o src/loko.cpp

database.o: src/database.cpp src/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o src/database.cpp

iconview.o: src/dialogs/iconview.cpp src/dialogs/iconview.h \
		ui_iconview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconview.o src/dialogs/iconview.cpp

cell.o: src/cell.cpp src/general.h \
		src/element.h \
		src/cell.h \
		src/view.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o src/cell.cpp

element.o: src/element.cpp src/general.h \
		src/mainwindow.h \
		src/element.h \
		src/cell.h \
		src/grid.h \
		src/document.h \
		src/lokocommands.h \
		src/route.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o element.o src/element.cpp

program.o: src/program.cpp src/general.h \
		src/lokocommands.h \
		src/conditions.h \
		src/route.h \
		src/program.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o src/program.cpp

route.o: src/route.cpp src/general.h \
		src/lokocommands.h \
		src/element.h \
		src/cell.h \
		src/grid.h \
		src/document.h \
		src/loko.h \
		src/conditions.h \
		src/route.h \
		src/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o route.o src/route.cpp

lokocommands.o: src/lokocommands.cpp src/general.h \
		src/lokocommands.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lokocommands.o src/lokocommands.cpp

conditions.o: src/conditions.cpp src/conditions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o conditions.o src/conditions.cpp

view.o: src/view.cpp src/general.h \
		src/element.h \
		src/cell.h \
		src/view.h \
		src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o src/view.cpp

plugindialog.o: src/plugindialog.cpp src/traininterface.h \
		src/plugindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plugindialog.o src/plugindialog.cpp

traininterface.o: src/traininterface.cpp src/general.h \
		src/traininterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o traininterface.o src/traininterface.cpp

debug.o: src/debug.cpp src/debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug.o src/debug.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_editlokos.o: moc_editlokos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editlokos.o moc_editlokos.cpp

moc_lokotabbar.o: moc_lokotabbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lokotabbar.o moc_lokotabbar.cpp

moc_lokodock.o: moc_lokodock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lokodock.o moc_lokodock.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

moc_iconview.o: moc_iconview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_iconview.o moc_iconview.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_plugindialog.o: moc_plugindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plugindialog.o moc_plugindialog.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_bitmaps.o: qrc_bitmaps.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_bitmaps.o qrc_bitmaps.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

